services:
  adminer:
    image: adminer
    restart: no
    ports:
      - 8080:8080

  postgres:
    container_name: postgres
    restart: no
    image: postgres:latest
    environment:
      POSTGRES_DB: "postiedb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    restart: no
    image: redis:alpine
    command: ["redis-server","/etc/redis/redis.conf"]
    volumes:
      - /redis/redis-data:/var/lib/redis
      - /redis/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    depends_on:
      - zookeeper
    
  kafka-init:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    entrypoint: 
      - /bin/sh
      - -c
      - |
        while ! nc -z kafka 29092;
        do
          echo "Waiting Kafka..."
          sleep 1
        done
        echo "Start creating topics"
        kafka-topics --create --topic Audit --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1
        kafka-topics --create --topic Errors --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1
        kafka-topics --create --topic Heartbeat --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1

volumes:
  postgres-data:
  